resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.cn-chengdu.aliyuncs.com/greatsql-sigs/greatsql-operator
  newTag: 1.0.1-alpha-1-8-g15d7f80
