apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: greatsql-controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: greatsql-controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: greatsql
    app.kubernetes.io/part-of: greatsql
    app.kubernetes.io/managed-by: kustomize
  name: greatsql-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greatsql-controller-manager
  namespace: greatsql-system
  labels:
    control-plane: greatsql-controller-manager
    app.kubernetes.io/name: greatsql-controller-manager
    app.kubernetes.io/instance: greatsql-controller-manager
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      control-plane: greatsql-controller-manager
  replicas: 3
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: greatsql-controller-manager
    spec:
      affinity:
        podAntiAffinity:
          # 使用preferredDuringSchedulingIgnoredDuringExecution策略，这意味着调度器会尽量满足反亲和性要求，但如果无法满足也不会阻止Pod调度
          # 权重设置为100，表示这是一个重要的调度要求
          # 使用control-plane: greatsql-controller-manager标签来匹配operator的Pod
          # 使用kubernetes.io/hostname作为拓扑键，确保Pod分布在不同节点上
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  control-plane: greatsql-controller-manager
              topologyKey: kubernetes.io/hostname
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        runAsNonRoot: true
        # fix the error "open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied" when deploying projects on older versions of Kubernetes
        # view details: https://github.com/kubernetes/kubernetes/pull/89193
        fsGroup: 65532
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - name: manager
        image: registry.cn-beijing.aliyuncs.com/greatsql/greatsql-operator:latest
        args:
          - --leader-elect=true
          - --leader-elect-namespace=greatsql-system
        env:
          # 控制operator的协调（reconciliation）循环的时间间隔，10s
        - name: RECONCILIATION_INTERVAL
          value: "10s"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: greatsql-controller-manager-sa
      terminationGracePeriodSeconds: 10