---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-greatsql-greatsql-cn-v1-groupreplicationcluster
  failurePolicy: Fail
  name: mgroupreplicationcluster.kb.io
  rules:
  - apiGroups:
    - greatsql.greatsql.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groupreplicationclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-greatsql-greatsql-cn-v1-groupreplicationcluster
  failurePolicy: Fail
  name: vgroupreplicationcluster.kb.io
  rules:
  - apiGroups:
    - greatsql.greatsql.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - groupreplicationclusters
  sideEffects: None
