# permissions for end users to edit GroupReplicationClusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: GroupReplicationCluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: greatsql
    app.kubernetes.io/part-of: greatsql
    app.kubernetes.io/managed-by: kustomize
  name: GroupReplicationCluster-editor-role
rules:
- apiGroups:
  - greatsql.greatsql.cn
  resources:
  - GroupReplicationClusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greatsql.greatsql.cn
  resources:
  - GroupReplicationClusters/status
  verbs:
  - get
