apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: greatsql-controller-manager
    app.kubernetes.io/component: rbac
  name: greatsql-controller-manager-sa
  namespace: greatsql-system