apiVersion: database.greatsql.cn/v1alpha1
kind: GroupReplicationCluster
metadata:
  name: greatsql-mgr
  namespace: greatsql
  labels:
    app.kubernetes.io/name: greatsql-mgr
    app.kubernetes.io/instance: greatsql-mgr
    app.kubernetes.io/component: controller
  finalizers:
    - finalizer.greatsql.cn
spec:
  mode: "single"
  member:
    - role: primary
      size: 1
    - role: secondary
      size: 2
    - role: arbitrator
      size: 1
  version: "8.0.26"
  serviceAccountName: default
  serviceName: greatsql-mgr-headless

  containers:
    - name: mysql
      image: greatsql/greatsql:8.0.32-26
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "2Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"
      startupProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        periodSeconds: 20
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        periodSeconds: 20
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 10
        periodSeconds: 30
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: greatsql-mgr-secret
              key: MYSQL_ROOT_PASSWORD

  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  priorityClassName: greatsql-priority
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  storages:
    storageClassName: ebs-gp3-sc
    accessModes: ["ReadWriteOnce"]
    volumeMode: Filesystem
    size: "5Gi"

  upgrade:
    versionServiceEndpoint: ""
    apply: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 1
  
  service:
    type: LoadBalancer
    selector:
      app: greatsql
    loadBalancerClass: "service.k8s.aws/nlb"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
