apiVersion: database.greatsql.cn/v1alpha1
kind: Standalone
metadata:
  name: greatsql-standalone
  namespace: greatsql
  labels:
    app.kubernetes.io/name: greatsql
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: greatsql

spec:
  size: 1
  version: "8.0.32-26"
  serviceAccountName: greatsql
  serviceName: greatsql
  containers:
    - name: greatsql
      image: greatsql/greatsql:8.0.32-26
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      resources:
        requests:
          memory: "2Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"
      startupProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 30
        periodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: greatsql-secret
              key: MYSQL_ROOT_PASSWORD

  affinity:
    antiAffinityTopologyKey: "kubernetes.io/hostname"
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  schedulerName: default-scheduler
  terminationGracePeriodSeconds: 30
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  priorityClassName: greatsql-priority

  storages:
    storageClassName: ebs-gp3-sc
    accessModes: ["ReadWriteOnce"]
    volumeMode: Filesystem
    size: "10Gi"

  upgrade:
    versionServiceEndpoint: ""
    apply: ""
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: 1

  service:
    type: LoadBalancer
    selector:
      app: greatsql
    loadBalancerClass: "service.k8s.aws/nlb"
    annotations:
      service.kubernetes.io/aws-load-balancer-type: nlb