name: GreatSQL Operator CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: 'Setup Go'
          uses: actions/setup-go@v2
          with:
            go-version: '1.21'

        - name: 'Install Go dependencies'
          run: go mod download

        - name: 'Static code analysis'
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.59

        - name: 'Run tests'
          run: go test -v ./...

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to ACR
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.ACR_REGISTRY }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        
        - name: Build and push Docker images
          run: |
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-6)
            IMAGE_TAG=${{ github.repository }}:${SHORT_SHA}
            docker buildx build --push --tag registry.cn-chengdu.aliyuncs.com/greatsql/greatsql-operator:${SHORT_SHA} .
            docker tag registry.cn-chengdu.aliyuncs.com/greatsql/greatsql-operator:${SHORT_SHA} registry.cn-chengdu.aliyuncs.com/greatsql/greatsql-operator:latest

        - name: 'Create a release for Tag'
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release GreatSQL Operator-v${{ github.ref }}
            prerelease: false
            body: |
              请点击查看 [更新日志](https://github.com/greatsql-sigs/greatsql-operator/blob/main/CHANGELOG.md).