---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greatsql-rolebinding
  namespace: greatsql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: greatsql-role
subjects:
- kind: ServiceAccount
  name: greatsql-sa
  namespace: greatsql
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greatsql-sa
  namespace: greatsql